import React from 'react';
import Head from 'next/head';
import { Footer } from 'src/components/Footer';
import { Header } from 'src/components/Header';
import { Post } from 'src/components/Post';

import styles from 'src/styles/Main.module.scss';

const data = [
  {
    postId: 1,
    date: '02 de jul, 2021',
    title: 'Agora é oficial: o Windows 11 está vindo',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum auctor est. Nam vitae finibus ante. Duis lobortis tellus vel diam fringilla, eu ullamcorper ex iaculis.',
    favorite: false,
  },
  {
    postId: 2,
    date: '02 de jul, 2021',
    title: 'Tim Berners-Lee vai leiloar código-fonte da web',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum auctor est. Nam vitae finibus ante. Duis lobortis tellus vel diam fringilla, eu ullamcorper ex iaculis. Praesent et auctor justo. Vestibulum nisl orci, lacinia venenatis leo sit amet, pulvinar tincidunt risus. Phasellus nisl dui, cursus a lectus et, interdum ullamcorper libero.',
    favorite: false,
  },
  {
    postId: 3,
    date: '02 de jul, 2021',
    title: 'Tem Firefox novo no pedaço e você vai querer migrar',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum auctor est.',
    favorite: false,
  },
  {
    postId: 4,
    date: '02 de jul, 2021',
    title: 'John McAfee, criador do antivírus McAfee, morre',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum auctor est. Nam vitae finibus ante. Duis lobortis tellus vel diam fringilla, eu ullamcorper ex iaculis. Praesent et auctor justo. Vestibulum nisl orci, lacinia venenatis leo sit amet, pulvinar tincidunt risus. Phasellus nisl dui, cursus a lectus et, interdum ullamcorper libero.',
    favorite: false,
  },
];

export default function Home() {
  const [favorites, setFavorites] = React.useState(data);

  React.useEffect(() => {
    function load() {
      const dataFavorites = JSON.parse(localStorage.getItem('@favorites'));
      dataFavorites?.length > 0 && setFavorites(dataFavorites);
    }

    load();
  }, []);

  function handleFavorite(obj) {
    const newFavorites = favorites;
    const data = newFavorites.find((el) => el.postId === obj.postId);
    data.favorite = obj.favorite;
    setFavorites(newFavorites);
    console.log(newFavorites);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@400;500&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
          referrerpolicy="no-referrer"
        />
      </Head>
      <Header />
      <div className={styles.container}>
        {favorites?.map((el) => {
          return (
            <Post
              key={el.postId}
              postId={el.postId}
              date={el.date}
              title={el.title}
              content={el.content}
              favorite={el.favorite}
              makeFavorite={(a) => handleFavorite(a)}
            />
          );
        })}
      </div>
      <Footer />
    </div>
  );
}
